#
# CheapGlk SConscript file.
#
# For the license of this file, please consult the LICENSE file in the
# root directory of this distribution.
#

# ----------------------------------------------------------------------------
# Imports
# ----------------------------------------------------------------------------

import glob

Import( "env" )


# ----------------------------------------------------------------------------
# Build Actions
# ----------------------------------------------------------------------------

env = env.Copy()

# For MSVC, we need to specify the export definition file to tell MSVC
# what functions to export in our DLL.
env.addToListVariable(
    env.LINKER_OPTIONS,
    env.MSVC,
    [ "/DEF:%s" % File( "cheapglk.def" ).path ]
    )

glkLib = env.LoadableModule(
    target = "libcheapglk",
    source = [ glob.glob( "*.c" ) ]
    )
